// <auto-generated />
using System;
using AirlineManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlineManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221108171822_addtable")]
    partial class addtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirlineManagementSystem.Models.AdminModel", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("AdminId");

                    b.ToTable("Tbl_Admin");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.AeroPlaneModel", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APlaneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.HasKey("PlaneId");

                    b.ToTable("Tbl_AeroPlane");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.FlightBookingModel", b =>
                {
                    b.Property<int>("Bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResId")
                        .HasColumnType("int");

                    b.Property<string>("bCusAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bCusCnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bCusEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bCusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bCusPhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bCusSeats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fligthDetailsModelResID")
                        .HasColumnType("int");

                    b.HasKey("Bid");

                    b.HasIndex("fligthDetailsModelResID");

                    b.ToTable("Tbl_FlightBooking");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.FlightDetailsModel", b =>
                {
                    b.Property<int>("ResID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlaneId")
                        .HasColumnType("int");

                    b.Property<int>("PlaneSeat")
                        .HasColumnType("int");

                    b.Property<string>("ResDepDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResPlaneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ResTicketPrice")
                        .HasColumnType("real");

                    b.Property<string>("ResTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("plane_tblsPlaneId")
                        .HasColumnType("int");

                    b.HasKey("ResID");

                    b.HasIndex("plane_tblsPlaneId");

                    b.ToTable("Tbl_FlightDetails");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.ToTable("Tbl_User");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.FlightBookingModel", b =>
                {
                    b.HasOne("AirlineManagementSystem.Models.FlightDetailsModel", "fligthDetailsModel")
                        .WithMany("tblFlightBookings")
                        .HasForeignKey("fligthDetailsModelResID");
                });

            modelBuilder.Entity("AirlineManagementSystem.Models.FlightDetailsModel", b =>
                {
                    b.HasOne("AirlineManagementSystem.Models.AeroPlaneModel", "plane_tbls")
                        .WithMany()
                        .HasForeignKey("plane_tblsPlaneId");
                });
#pragma warning restore 612, 618
        }
    }
}
